// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Comm2Tender.Models;

public class AdditionalСondition
{
    public int Id { get; set; }

    public double? Expireence { get; set; }

    public double? Market { get; set; }

    public double? Fines { get; set; }

    public bool? IsDirectCounterparty { get; set; }

    public double? InventoryCount { get; set; }

    public double? Equipment { get; set; }

    public double? Geografy { get; set; }

    public double? Loyality { get; set; }

    public double? Complaint { get; set; }

    public DateOnly? DateInsert { get; set; }
}