// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace Comm2Tender.Models;

public class DictContragent
{
    public int Id { get; set; }

    [JsonProperty(PropertyName = "Counterparty")]
    public string Counterparty { get; set; }

    public int? SystemNum { get; set; }

    public DateTime? DateContract { get; set; }

    public bool? IsDirectCounterparty { get; set; }

    public DateTime? DateRegContragent { get; set; }

    public DateTime? DatePartnership { get; set; }

    public virtual ICollection<LogTender> LogTenders { get; set; }
}