// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Comm2Tender.Models;

public partial class EconomicEffectVar
{
    public int Id { get; set; }

    [JsonPropertyName("PrepaidExpense1")]
    public double? PrepaidExpense { get; set; }

    [JsonPropertyName("PeriodOfExecution1")]
    public int? PeriodOfExecution { get; set; }

    [JsonPropertyName("PostPaymant1")]
    public int? Postpayment { get; set; }

    [JsonPropertyName("PostPaymantPeriod1")]
    public int? PostpaymentPeriod { get; set; }

    public int? IdTendes { get; set; }

    [JsonPropertyName("PrepaidExpense2")]
    public double? PrepaidExpense2 { get; set; }

    [JsonPropertyName("PeriodOfExecution2")]
    public int? PeriodOfExecution2 { get; set; }

    [JsonPropertyName("PostPaymant2")]
    public int? Postpayment2 { get; set; }

    [JsonPropertyName("PostPaymantPeriod2")]
    public int? PostpaymentPeriod2 { get; set; }

    [JsonPropertyName("PrepaidExpense3")]
    public double? PrepaidExpense3 { get; set; }

    [JsonPropertyName("PeriodOfExecution3")]
    public int? PeriodOfExecution3 { get; set; }

    [JsonPropertyName("PostPaymant3")]
    public int? Postpayment3 { get; set; }

    [JsonPropertyName("PostPaymantPeriod3")]
    public int? PostpaymentPeriod3 { get; set; }

    [JsonPropertyName("Accreditive")]
    public bool? IsAccredetive { get; set; }

    [JsonPropertyName("CustomDuty")]
    public bool? IsCustomsDuty { get; set; }

    [JsonPropertyName("CustomFee")]
    public bool? IsCustomsFee { get; set; }

    [JsonPropertyName("BankGuarantee")]
    public bool? IsBankGuarantee { get; set; }

    public bool MissingDeadlines { get; set; }

    public bool PoorQuality { get; set; }

    public bool NormsViolated { get; set; }
}