// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Comm2Tender.Models;

public partial class EconomicEffect
{
    public int Id { get; set; }

    public double? PrepaidExpense { get; set; }

    public int? PeriodOfExecution { get; set; }

    public int? Postpayment { get; set; }

    public int? PostpaymentPeriod { get; set; }

    public int? IdTendes { get; set; }

    public double? PrepaidExpense2 { get; set; }

    public int? PeriodOfExecution2 { get; set; }

    public int? Postpayment2 { get; set; }

    public int? PostpaymentPeriod2 { get; set; }

    public double? PrepaidExpense3 { get; set; }

    public int? PeriodOfExecution3 { get; set; }

    public int? Postpayment3 { get; set; }

    public int? PostpaymentPeriod3 { get; set; }

    public bool? IsAccredetive { get; set; }

    public bool? IsCustomsDuty { get; set; }

    public bool? IsCustomsFee { get; set; }

    public bool? IsBankGuarantee { get; set; }

    public virtual LogTender IdTendesNavigation { get; set; }
}