// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace Comm2Tender.Models;

public class EconomicEffectVar
{
    public int Id { get; set; }

    [JsonProperty(PropertyName = "PrepaidExpense1")]
    public double? PrepaidExpense { get; set; }

    [JsonProperty(PropertyName = "PeriodOfExecution1")]
    public int? PeriodOfExecution { get; set; }

    [JsonProperty(PropertyName = "PostPaymant1")]
    public int? Postpayment { get; set; }

    [JsonProperty(PropertyName = "PostPaymantPeriod1")]
    public int? PostpaymentPeriod { get; set; }

    public int? IdTendes { get; set; }

    [JsonProperty(PropertyName = "PrepaidExpense2")]
    public double? PrepaidExpense2 { get; set; }

    [JsonProperty(PropertyName = "PeriodOfExecution2")]
    public int? PeriodOfExecution2 { get; set; }

    [JsonProperty(PropertyName = "PostPaymant2")]
    public int? Postpayment2 { get; set; }

    [JsonProperty(PropertyName = "PostPaymantPeriod2")]
    public int? PostpaymentPeriod2 { get; set; }

    [JsonProperty(PropertyName = "PrepaidExpense3")]
    public double? PrepaidExpense3 { get; set; }

    [JsonProperty(PropertyName = "PeriodOfExecution3")]
    public int? PeriodOfExecution3 { get; set; }

    [JsonProperty(PropertyName = "PostPaymant3")]
    public int? Postpayment3 { get; set; }

    [JsonProperty(PropertyName = "PostPaymantPeriod3")]
    public int? PostpaymentPeriod3 { get; set; }

    [JsonProperty(PropertyName = "Accreditive")]
    public bool? IsAccredetive { get; set; }

    [JsonProperty(PropertyName = "CustomDuty")]
    public bool? IsCustomsDuty { get; set; }

    [JsonProperty(PropertyName = "CustomFee")]
    public bool? IsCustomsFee { get; set; }

    [JsonProperty(PropertyName = "BankGuarantee")]
    public bool? IsBankGuarantee { get; set; }

    public VarContragentOfTender IdNavigation { get; set; }
}