// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Comm2Tender.Models;

public class InterestRate
{
    public int Id { get; set; }

    public double? RateCb { get; set; }

    public double? PersTmk { get; set; }

    public double? PersBank { get; set; }

    public double? PersCustoms { get; set; }

    public double? PersDiscount { get; set; }

    public double? PersBillOfCreadit { get; set; }

    public virtual ICollection<LogTender> LogTenders { get; set; }
}