// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Comm2Tender.Models;

public class ListClaim
{
    public int Id { get; set; }

    public int? IdPosTender { get; set; }

    public int? IdClaim { get; set; }

    public bool? IsFMaejuere { get; set; }

    public DateOnly? DateCorrection { get; set; }

    public virtual DictClaim IdClaimNavigation { get; set; }

    public virtual PosTender IdPosTenderNavigation { get; set; }
}