// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Comm2Tender.Models;

public class LogTender
{
    public int Id { get; set; }

    public int? IdCounterparty { get; set; }

    public string NumTender { get; set; }

    public int? IdInterestRate { get; set; }

    public int? IdСustomsDuty { get; set; }

    public double? ReliabilityAssessment { get; set; }

    public DateOnly? DateTender { get; set; }

    public  ICollection<EconomicEffect> EconomicEffects { get; set; }

    public  DictContragent IdCounterpartyNavigation { get; set; }

    public  InterestRate IdInterestRateNavigation { get; set; }

    public  СustomsDuty IdСustomsDutyNavigation { get; set; }

    public  ICollection<PosTender> PosTenders { get; set; }
}