// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Comm2Tender.Models;

public partial class LogTender
{
    public int Id { get; set; }

    public int? IdCounterparty { get; set; }

    public string NumTender { get; set; }

    public int? IdInterestRate { get; set; }

    public int? IdСustomsDuty { get; set; }

    public double? ReliabilityAssessment { get; set; }

    public DateOnly? DateTender { get; set; }

    public virtual ICollection<EconomicEffect> EconomicEffects { get; set; } = new List<EconomicEffect>();

    public virtual DictContragent IdCounterpartyNavigation { get; set; }

    public virtual InterestRate IdInterestRateNavigation { get; set; }

    public virtual СustomsDuty IdСustomsDutyNavigation { get; set; }

    public virtual ICollection<PosTender> PosTenders { get; set; } = new List<PosTender>();
}