// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Comm2Tender.Models;

public class PosTender
{
    public int Id { get; set; }

    public int? CountPos { get; set; }

    public double? PositionPrice { get; set; }

    public double? DeliveryCost { get; set; }

    public int? IdTender { get; set; }

    public DateOnly? DateDelivery { get; set; }

    public DateOnly? DatePlanDelivery { get; set; }

    public int? CountDayDelivery { get; set; }

    public LogTender IdTenderNavigation { get; set; }

    public ICollection<ListClaim> ListClaims { get; set; }
}