// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Comm2Tender.Models;

public class СustomsDuty
{
    public int Id { get; set; }

    public double? MinPrice { get; set; }

    public double? MaxPrice { get; set; }

    public double? SumСustomsDuty { get; set; }

    public ICollection<LogTender> LogTenders { get; set; }
}